apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cyclictest
  namespace: openshift-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cyclictest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cyclictest
        app.kubernetes.io/version: v1.0.0
      name: cyclictest
      namespace: openshift-monitoring
    spec:
      tolerations:
        - operator: Exists
      containers:
      - name: cyclictest
        volumeMounts:
          - mountPath: /dev/cpu_dma_latency
            name: dev-cpu-dma-latency
        image: quay.io/ayosef/cyclictest
        imagePullPolicy: IfNotPresent
        args:
          - --smp
          - -p95
        securityContext:
          privileged: true
          capabilities:
            add:
              - ipc_lock
              - sys_nice
              - sys_rawio
        resources:
            requests:
              cpu: 8m
              memory: 180Mi
        restartPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/worker-cnf: ''
      volumes:
      - name: dev-cpu-dma-latency
        hostPath:
          path: /dev/cpu_dma_latency
